YouTubeDownloader/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('YouTubeDownloaderApp.urls')),
]

YouTubeDownloaderApp/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name='ytproject'

urlpatterns = [
    path('', views.index, name='home'),
    path('download', views.download, name='download'),
    path('download/<resolution>', views.yt_download_done, name='download_done'),


    # path('admin/', admin.site.urls),
    # path('', include('YouTubeDownloaderApp.urls')),
]

YouTubeDownloaderApp/models.py
from django.db import models

# Create your models here.

YouTubeDownloaderApp/views.py
from django.shortcuts import render
from pytube import *
import os
from django.conf.urls import *
global url
global strms

# Create your views here.
def index(request):
    return render(request, 'index.html')

def download(request):
    global url
    url = request.GET.get('url') #,'')
    if url== "":
        return render(request,'empty.html')
    yt= YouTube(url)
    strms= []
    strms= yt.streams.filter(progressive=True).all
    embed_link= url.replace("watch?v=","embed/")
    Title = yt.title
    params={'title': Title, 'strms': strms, 'embed': embed_link, 'url': url}#, 'size': size}
    return render(request, 'download.html', params)

def yt_download_done(request,resolution):
    global url
    homedir = os.path.expanduser("~")
    dirs = homedir + "/Downloads"
    if request.method == 'POST':
        YouTube(url).streams.get_by_resolution(resolution).download(dirs)
        return render(request, 'done.html')

    else:
        return render(request, 'error.html')

YouTubeDownloaderApp/templates/basic.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-tofit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.1/css/bootstrap.min.css"
          integrity="sha384-VCmXjywReHh4PwowAiWNagnWcLhlEJLA5buUprzK8rxFgeH0kww/aWY76TfkUoSX"
          crossorigin="anonymous">
    <title>
        {% block title %}
        {% endblock %}</title>
    <link rel="shortout icon" type="image/x-icon" href="{%static 'YouTubeDownloaderApp/favicon.ico' %}"/>
    <style>
    bac {
  opacity: 0.5;
}
        body {
  background-image: url("{%static 'YouTubeDownloaderApp/download.png' %}");
  left: 0;
  right: 0;
  height: auto;
  background-repeat: no-repeat;
  background-color: pink;
  background-size: cover;
}
    </style>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand color" href="/"><strong>YouTube Downloader</strong></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
                <a href="https://chat.whatsapp.com/KjwbLh0i5D0DM4WA4uLnmj" target="_blank" class="btn btn-outline-warning btn-sm " role="button" aria-pressed="true">WhatsApp Status Downloader</a>
            </li>
            &nbsp;&nbsp;&nbsp;
            <li class="nav-item">
                <a href="https://www.instagram.com/o_world0/" target="_blank" class="btn btn-outline-danger btn-sm " role="button" aria-pressed="true">Instagram Post Downloader</a>

            </li>
        </ul>
    </div>
</nav>

{% block body %}
{% endblock %}

<br>
<br>
<br>
<br>


<footer class="container">
    <p class="float-right"><a href="#">Back to top</a></p>
    <p>© 2020 <a href="/">YouTube Downloader</a>, Inc. · <a href="#">Privacy</a> · <a href="#">Terms</a></p>
</footer>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-
DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
<script
        src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.1/js/bootstrap.min.js"
        integrity="sha384-XEerZL0cuoUbHE4nZReLT7nx9gQrQreJekYhJD9WNWhH8nEW+0c5qq7aIo2Wl30J"
        crossorigin="anonymous"></script>
</body>
</html>

YouTubeDownloaderApp/templates/done.html
{% extends 'basic.html' %}
 {% block title %}
 Download
{% endblock %}

{% block body %}
<center>
<br><h2>Download done</h2>

<br><br><a href="/" class="btn btn-outline-danger btn-lg " role="button" aria-pressed="true">Back to Home</a><br><br>
</center>
<br><br><br><br><br><br><br><br><br><br><br><br>
{% endblock%}

YouTubeDownloaderApp/templates/download.html
{% extends 'basic.html' %}
 {% block title %}
 YouTube Video Resolutions
{% endblock %}

{% block body %}

<div class="container mt-4">
    <div class="embed-responsive embed-responsive-21by9">
        <iframe class="embed-responsive-item" src={{embed}} allowfullscreen></iframe>
    </div>
    <br>
    <h4>Title: {{title}}</h4>
</div>

<div class="container my-5">
    <table class="table">
        <thead class="thead-dark">
        <tr>
            <th scope="col">Quality</th>
            <th scope="col">Type</th>
            <th scope="col">Size</th>
            <th scope="col">Download</th>
        </tr>
        </thead>
        {% for j in strms %}
        <tbody>
        <tr>
            <th>{{j.resolution}}</th>
            <td>{{j.mime_type}}</td>
            <td>{{j.filesize}} Bytes</td>
            <td>
                <form action="{% url 'ytproject:download_done' j.resolution %}" method="post">
                    {% csrf_token %}
                    <input type="submit" class="btn btn-success" value="Download">
                </form>
        </tr>
        </tbody>
        {% endfor %}
    </table>
</div>

{% endblock %}

YouTubeDownloaderApp/templates/empty.html
{% extends 'basic.html' %}
 {% block title %}
 URL Box Empty. Pleas enter a YouTube video URL!
{% endblock %}
 {% block body %}
<center>
<h1>Error:</h1>
    <br><br>
    <h3>Pleas enter a YouTube video URL in URL box.</h3>
    <br><br><br>
<a href="/" class="btn btn-outline-danger btn-lg " role="button" aria-pressed="true">Back to Home</a>
</center>


<br><br><br><br><br><br><br><br><br>
{% endblock %}

YouTubeDownloaderApp/templates/error.html
{% extends 'basic.html' %}
 {% block title %} Something went wrong! {% endblock %}

{% block body %}
<h1>Error:</h1>
    <br><br>
    <h3>Something went wrong! Pleas try again.</h3>
    <br><br><br>
<a href="/" class="btn btn-outline-danger btn-lg " role="button" aria-pressed="true">Back to Home</a>
</center>


<br><br><br><br><br><br><br><br>
{% endblock %}

YouTubeDownloaderApp/templates/index.html
{% extends 'basic.html' %}
 {% block title %}
 YouTube Downloader . The Best YouTube Video downloader!
{% endblock %}
 {% block body %}
  <marquee style="color: green" ><strong>Welcome to YouTube Downloader! You can download YouTube video(s).</strong></marquee>
    <div class="container mt-5">
     <center><h1>Enter YouTube Video URL (Link)</h1></center>
 </div>

 <div class="container mt-5">
     <center>
         <form action='download' method="get" >
<!--             {% csrf_token %}-->
<!--             method='post'-->
         <div class="form-group">
             <input name='url' type="text" class="form-control" placeholder="Enter YouTube video URL here">
         </div>
         <button type="submit" class="btn btn-danger ">Proceed to Download</button>
     </form>
     </center>
 </div>
<br><br><br><br><br><br><br><br><br>
{% endblock %}